#!/usr/bin/env python3
"""Generate the WiFi join QR code the ROM manager draws on its screen.

The credentials are compile-time constants, so the code is generated once here
rather than by an encoder in the firmware. If you change the access point's name
or password in manager/main/web.c, run this again:

    python3 tools/mk_wifiqr.py

The payload is the convention phones understand: scanning it with the camera
offers to join the network, which is the part that would otherwise mean typing a
twelve-character password on a phone keyboard.

Usage: mk_wifiqr.py [ssid] [password] > manager/main/wifiqr.h
"""
import sys

import qrcode


def main():
    ssid = sys.argv[1] if len(sys.argv) > 1 else "gameboy-rlcd"
    password = sys.argv[2] if len(sys.argv) > 2 else "gameboy1234"

    # WPA with a passphrase, escaped as the convention requires.
    payload = f"WIFI:T:WPA;S:{ssid};P:{password};;"

    # Error correction L keeps the code small; nothing is going to damage a
    # screen that is being photographed from 20 cm away.
    code = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_L, border=0)
    code.add_data(payload)
    code.make(fit=True)

    matrix = code.get_matrix()
    size = len(matrix)
    if size > 64:
        raise SystemExit(f"code is {size}x{size}, too large to draw")

    rows = []
    for row in matrix:
        bits = 0
        for col, on in enumerate(row):
            if on:
                bits |= 1 << (size - 1 - col)
        rows.append(bits)

    print("// Generated by tools/mk_wifiqr.py - do not edit.")
    print(f'// "WIFI:T:WPA;S:{ssid};P:{password};;" as a {size}x{size} QR code,')
    print("// one bit per module, most significant bit leftmost.")
    print("#pragma once")
    print()
    print("#include <stdint.h>")
    print()
    print(f"#define WIFIQR_SIZE {size}")
    print()
    print(f"static const uint64_t kWifiQr[{size}] = {{")
    digits = (size + 3) // 4
    for i, bits in enumerate(rows):
        # Hex, not the binary digits the rows are held as: "0x" followed by 0s
        # and 1s is still a hex literal to a C compiler, and reads as something
        # entirely different.
        print(f"    0x{bits:0{digits}x}ULL, // row {i}")
    print("};")


if __name__ == "__main__":
    main()
