// Generated by tools/mk_wifiqr.py - do not edit.
// "WIFI:T:WPA;S:gameboy-rlcd;P:gameboy1234;;" as a 29x29 QR code,
// one bit per module, most significant bit leftmost.
#pragma once

#include <stdint.h>

#define WIFIQR_SIZE 29

static const uint64_t kWifiQr[29] = {
    0x1fce947fULL, // row 0
    0x10439041ULL, // row 1
    0x174e265dULL, // row 2
    0x1756c85dULL, // row 3
    0x1755475dULL, // row 4
    0x104c9d41ULL, // row 5
    0x1fd5557fULL, // row 6
    0x00094100ULL, // row 7
    0x18ed9a18ULL, // row 8
    0x15942791ULL, // row 9
    0x075b71e8ULL, // row 10
    0x1e863451ULL, // row 11
    0x0f5c5451ULL, // row 12
    0x150dfb74ULL, // row 13
    0x14e8ad24ULL, // row 14
    0x1595328fULL, // row 15
    0x0359a22bULL, // row 16
    0x121cf358ULL, // row 17
    0x1f596fddULL, // row 18
    0x123e5693ULL, // row 19
    0x15462dfcULL, // row 20
    0x001de913ULL, // row 21
    0x1fd0ff54ULL, // row 22
    0x1059971aULL, // row 23
    0x174793f6ULL, // row 24
    0x174c3699ULL, // row 25
    0x17473afeULL, // row 26
    0x1052109dULL, // row 27
    0x1fd22a18ULL, // row 28
};
